import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#0d1322',
        'surface-dim': '#0d1322',
        'surface-bright': '#333949',
        'surface-container-lowest': '#080e1d',
        'surface-container-low': '#151b2b',
        'surface-container': '#191f2f',
        'surface-container-high': '#242a3a',
        'surface-container-highest': '#2f3445',
        'surface-variant': '#2f3445',
        'surface-tint': '#adc6ff',
        'on-surface': '#dde2f7',
        'on-surface-variant': '#c2c6d6',
        'inverse-surface': '#dde2f7',
        'inverse-on-surface': '#2a3040',
        outline: '#8c909f',
        'outline-variant': '#424754',
        background: '#0d1322',
        'on-background': '#dde2f7',
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'inverse-primary': '#005ac2',
        secondary: '#a4c9ff',
        'on-secondary': '#00315d',
        'secondary-container': '#0267b8',
        'on-secondary-container': '#d6e5ff',
        tertiary: '#bcc7de',
        'on-tertiary': '#263143',
        'tertiary-container': '#8691a7',
        'on-tertiary-container': '#1f2a3c',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'secondary-fixed': '#d4e3ff',
        'secondary-fixed-dim': '#a4c9ff',
        'on-secondary-fixed': '#001c39',
        'on-secondary-fixed-variant': '#004883',
        'tertiary-fixed': '#d8e3fb',
        'tertiary-fixed-dim': '#bcc7de',
        'on-tertiary-fixed': '#111c2d',
        'on-tertiary-fixed-variant': '#3c475a',
      },
      fontFamily: {
        display: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        body: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        code: ['JetBrains Mono', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'code-sm': ['13px', { lineHeight: '1.4', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      boxShadow: {
        liquid: 'inset 0 1px 1px rgba(255, 255, 255, 0.05), 0 10px 30px -10px rgba(0, 0, 0, 0.5)',
        'liquid-strong': 'inset 0 0 10px rgba(255, 255, 255, 0.05), 0 24px 60px rgba(0, 0, 0, 0.4)',
        bloom: '0 0 20px rgba(173, 198, 255, 0.16)',
      },
      backgroundImage: {
        'cyber-grid': 'linear-gradient(rgba(173, 198, 255, 0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(173, 198, 255, 0.08) 1px, transparent 1px)',
        'surface-radial': 'radial-gradient(circle at top, rgba(30, 41, 59, 0.9) 0%, rgba(13, 19, 34, 1) 65%)',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 0 rgba(173, 198, 255, 0.12)' },
          '50%': { boxShadow: '0 0 24px rgba(173, 198, 255, 0.22)' },
        },
      },
      animation: {
        float: 'float 7s ease-in-out infinite',
        glow: 'pulseGlow 4.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;
